name: Build Image

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout code
        if: github.event_name == 'push'
        uses: actions/checkout@v4

  build-image:
    needs: checkout
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: directory-size-exporter
      dockerfile: ./Dockerfile
      context: .

  list-images:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: List images
        run: |
          echo "${{ needs.build-image.outputs.images }}"
